Secure phillip's page
CLSB-Programming/clsb-programming.github.io pull request #75
Opened 2017-03-13 20:16 UTC by Prouser123

I like https. 👍

2017-03-13 20:59 UTC, domdomegg commented
Might be a bit risky storing that image of a cookie - potential copyright violation. Try using a HTTPS origin or a freely licensed picture instead

2017-03-13 21:00 UTC, domdomegg requested changes
Use `https://vignette2.wikia.nocookie.net/mspafetchmodus/images/a/ab/Chocolate_chip_cookie.jpg/revision/latest?cb=20100726200146` as source instead of hosting image ourselves

2017-03-14 13:17 UTC, Prouser123 commented
Done @domdomegg

2017-03-14 16:04 UTC, domdomegg approved these changes

2017-03-14 16:04 UTC, merged